backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("usuario/", include("usuario.urls")),
    path('mapa/', include("mapa.urls")),
    path('ponto/', include('ponto.urls')),
]

home/urls.py
from django.urls import include, path

from home import views

urlpatterns = [
    path('',views.index, name='index'),
    path('mapa/', include("mapa.urls")),
    
]

mapa/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('mapa/',views.mostrar_mapa, name='mapa'),
    path('ponto/', include('ponto.urls')),
    path('cad_endereco/', include('cad_endereco.urls')),
]

ponto/urls.py
from django.urls import path
from . import views as v

app_name = 'ponto'

urlpatterns = [
    path('geojson/', v.PontoGeojson.as_view(), name='ponto-geojson'),
    path('pontos.js/', v.pontos_js, name='pontos_js'),
]

mapa/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required 


@login_required
def mostrar_mapa(request):
    return render(request, 'mapa/mapa.html')

mapa/templates/mapa/mapa.html
{% load static %}

{% block extra_css %}
<link href="{% static 'libs\leaflet\leaflet.css' %}" rel="stylesheet">
<style>
    #map {
        height: 600px;
        /* Ou 100vh para ocupar a altura da tela toda */
        width: 100%;
    }
</style>

{% endblock extra_css %}


{% block content %}
<div id="map"></div>

<input type="hidden" id="pontos_geojson" value="{% url 'ponto:ponto-geojson' %}">
<input type="hidden" id="pontos_js" value="{% url 'ponto:pontos_js' %}">
{% endblock content %}


{% block extra_js %}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'libs\leaflet\leaflet.js' %}"></script>
<script src="{% static 'libs\leaflet-heat\leaflet-heat.js' %}"></script>
<script src="{% url 'ponto:pontos_js' %}"></script>
<script src="{% static 'js\map.js' %}"></script>

{% endblock extra_js %}